### Introduction To Pandas Module
Here, we are learning data analysis. Pandas is a software library written for the Python programming language that helps with data manipulation and analysis. It offers various data structures which help in the manipulation of data. <br>
One of the data structures used is DataFrame.<br>
DataFrame is used as a way to store data in a rectangular grid.<br>
Similar to how data is stored in Microsoft Excel.
### Installation
We can easily install this library using the terminal. Follow the steps given below to install Pandas:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install pandas with the help of pip easily. Head over to the directory where you want to install the pandas and fire the below command:<br>
__pip install pandas__<br>
This is very simple to install.

In [ ]:
# !pip install pandas

### Other way to install
If the above steps do not work for you, here is another way to install:<br>
Step 1: Go to your browser. Search for __python unofficial binaries__, or click <br>
https://www.lfd.uci.edu/~gohlke/pythonlibs/<br> 
and you will be redirected to the binary page.<br>
Step 2: To download the library, search for pandas – Ctrl + F will help you. Download pandas library based on your python version. <br>
Step 3: After the installation, head over to the directory where you've downloaded the pandas. <br>
Step 4: Right-click to open Windows PowerShell. Pip can help us with the installation. Just go to that location in your terminal and run the following command: <br>
__pip install pandas__ <br>
Complete this command by the TAB button so that the location of your folder is mentioned.

### import pandas
Once Pandas is installed, import it in your applications by adding the import keyword:<br>
__import pandas as pd__<br>
Now Pandas is imported and ready to use.

In [1]:
import pandas

In [2]:
students = {
    'Name': ["Muhammad Ayub ", " Ibraheem khan", "Muhammad Abid", "Shumail Khan","Qasim Ali"],
    'Marks': [80, 72, 77, 65, 15],
    'Class':["1st Year", "2nd Year", "1st Year", "3rd Year", "2nd Year"],
    'Age': [20, 21, 19, 22, 21]
}

In [3]:
df = pandas.DataFrame(students)

In [4]:
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

### Pandas as pd
Pandas is usually imported under the pd alias.
#### alias: 
In Python alias are an alternate name for referring to the same thing.<br>
Create an alias with the as keyword while importing:<br>
__import pandas as pd__<br>
Now the Pandas package can be referred to as pd instead of pandas.

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame(students)

In [7]:
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

### Checking Pandas Version
The version string is stored under __version__ attribute.

In [8]:
pd.__version__

'2.3.2'

## Saving to CSV and other extensions like excel

In [9]:
df.to_csv('pythonMonday.csv')

## Remove Index and saving the csv file

In [10]:
df.to_csv('pythonMondayRemoveIndex.csv', index=False)

## Show some rows from the Start

In [11]:
df.head()

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

## Specify No of rows to show

In [12]:
df.head(3)

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19

In [13]:
df.tail(3)

            Name  Marks     Class  Age
2  Muhammad Abid     77  1st Year   19
3   Shumail Khan     65  3rd Year   22
4      Qasim Ali     15  2nd Year   21

In [14]:
df.tail()

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [15]:
df.describe()

           Marks        Age
count   5.000000   5.000000
mean   61.800000  20.600000
std    26.771253   1.140175
min    15.000000  19.000000
25%    65.000000  20.000000
50%    72.000000  21.000000
75%    77.000000  21.000000
max    80.000000  22.000000

# Reading csv or other files

In [16]:
classData= pd.read_csv("pythonMondayRemoveIndex.csv")
classData

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [17]:
classData= pd.read_csv("pythonMonday.csv")
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [18]:
classData.drop('Name', axis=1)

   Unnamed: 0  Marks     Class  Age
0           0     80  1st Year   20
1           1     72  2nd Year   21
2           2     77  1st Year   19
3           3     65  3rd Year   22
4           4     15  2nd Year   21

In [19]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [20]:
classData.drop(0, axis=0)

   Unnamed: 0            Name  Marks     Class  Age
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [21]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

# Check the spelling

In [23]:
classData['Class']

0    1st Year
1    2nd Year
2    1st Year
3    3rd Year
4    2nd Year
Name: Class, dtype: object

# Check the trail space

In [31]:
classData['Class']

0    1st Year
1    2nd Year
2    1st Year
3    3rd Year
4    2nd Year
Name: Class, dtype: object

# Corrected Spelling

In [32]:
classData['Name']

0    Muhammad Ayub
1     Ibraheem khan
2     Muhammad Abid
3      Shumail Khan
4         Qasim Ali
Name: Name, dtype: object

# Check the head space

In [33]:
classData['Name']

0    Muhammad Ayub
1     Ibraheem khan
2     Muhammad Abid
3      Shumail Khan
4         Qasim Ali
Name: Name, dtype: object

In [34]:
type(classData['Name'])

pandas.core.series.Series

In [35]:
classData['Age']

0    20
1    21
2    19
3    22
4    21
Name: Age, dtype: int64

classData['gpa'][0]

In [36]:
classData['Age'][0]

np.int64(20)

In [37]:
classData['Age'][0]=90

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13556\883805414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  classData['Age'][0]=90

In [38]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   90
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [39]:
classData['Age'][4]

np.int64(21)

In [40]:
classData['Age'][4]=5

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13556\1411840039.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  classData['Age'][4]=5

In [41]:
classData["Name"][4]

'Qasim Ali'

# Rename the column name

In [42]:
classData.rename(columns={'Age': 'AGE'})

   Unnamed: 0            Name  Marks     Class  AGE
0           0  Muhammad Ayub      80  1st Year   90
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year    5

## Create Labels
With the index argument, you can name your own labels.

In [43]:
classData.index = ["First","Second", "Third", "Fourth", "Fifth"]
classData

        Unnamed: 0            Name  Marks     Class  Age
First            0  Muhammad Ayub      80  1st Year   90
Second           1   Ibraheem khan     72  2nd Year   21
Third            2   Muhammad Abid     77  1st Year   19
Fourth           3    Shumail Khan     65  3rd Year   22
Fifth            4       Qasim Ali     15  2nd Year    5

# Asignment

In [44]:
classdata = classData.drop('Unnamed: 0', axis=1)
classData

        Unnamed: 0            Name  Marks     Class  Age
First            0  Muhammad Ayub      80  1st Year   90
Second           1   Ibraheem khan     72  2nd Year   21
Third            2   Muhammad Abid     77  1st Year   19
Fourth           3    Shumail Khan     65  3rd Year   22
Fifth            4       Qasim Ali     15  2nd Year    5

# Inplace

In [45]:
classData.drop('Unnamed: 0', axis=1, inplace = True)
classData

                  Name  Marks     Class  Age
First   Muhammad Ayub      80  1st Year   90
Second   Ibraheem khan     72  2nd Year   21
Third    Muhammad Abid     77  1st Year   19
Fourth    Shumail Khan     65  3rd Year   22
Fifth        Qasim Ali     15  2nd Year    5

# Accessing the value in Dataframe

In [46]:
classData["Name"]

First     Muhammad Ayub
Second     Ibraheem khan
Third      Muhammad Abid
Fourth      Shumail Khan
Fifth          Qasim Ali
Name: Name, dtype: object

In [47]:
classData["Name"]["Fifth"]

'Qasim Ali'

## Pandas 
Pandas is an open source data analysis library written in Python.<br>
It uses the power and speed of numpy to make data analysis and preprocessing easy for data scientists.<br>
__Pandas__ is used to analyze data.<br>
Python data analysis using pandas is a great start to Exploratory Data Analysis (EDA) for a data scientist.

## Pandas Data Structure
Panda has two types of Data Structure:<br> 
    a) Series<br>
    b) Dataframe
### Series
It is a one dimentional array with indexes. It stores a single column or row of data in a Dataframe.<br>
It is a one dimensional array capable of holding any type of data.
### Dataframe
It is a tabular spreadsheet like structure representing rows each of which contains one or more columns.<br>
It is a multi dimensional array capable of holding any type of data.<br>
__Series__ is like a column, a __DataFrame__ is the whole table.

In [48]:
classData['Age']

First     90
Second    21
Third     19
Fourth    22
Fifth      5
Name: Age, dtype: int64

In [49]:
 type(classData['Age'])

pandas.core.series.Series

In [50]:
classData

                  Name  Marks     Class  Age
First   Muhammad Ayub      80  1st Year   90
Second   Ibraheem khan     72  2nd Year   21
Third    Muhammad Abid     77  1st Year   19
Fourth    Shumail Khan     65  3rd Year   22
Fifth        Qasim Ali     15  2nd Year    5

In [51]:
type(classData)

pandas.core.frame.DataFrame

In [52]:
import numpy as np

In [53]:
series1= pd.Series(np.random.rand())

In [54]:
series1

0    0.053186
dtype: float64

In [55]:
series1= pd.Series(np.random.rand(30))

In [56]:
series1

0     0.166945
1     0.504619
2     0.574777
3     0.390095
4     0.652689
5     0.118773
6     0.461982
7     0.642760
8     0.742631
9     0.976496
10    0.882412
11    0.979348
12    0.469004
13    0.248426
14    0.174619
15    0.662990
16    0.694088
17    0.969357
18    0.334406
19    0.146020
20    0.365996
21    0.316246
22    0.787200
23    0.761510
24    0.128960
25    0.345694
26    0.088655
27    0.594488
28    0.490935
29    0.080568
dtype: float64

In [57]:
type(series1)

pandas.core.series.Series

In [58]:
np.random.rand(3,4)

array([[0.58850385, 0.63860347, 0.55329815, 0.02530646],
       [0.35809543, 0.9422692 , 0.87676421, 0.91665503],
       [0.06115112, 0.99295516, 0.75108254, 0.4066263 ]])

In [59]:
newDf = pd.DataFrame(np.random.rand(330,5))
# newDf = pd.DataFrame(np.random.rand(330,5), index=np.arange(330))

In [60]:
type(newDf)

pandas.core.frame.DataFrame

In [61]:
newDf.head(2)

          0         1         2         3         4
0  0.215584  0.743549  0.157163  0.304643  0.893568
1  0.576556  0.624649  0.153145  0.416081  0.557485

In [62]:
newDf.tail(2)

            0         1         2         3         4
328  0.078529  0.333257  0.721789  0.901435  0.098185
329  0.122808  0.848746  0.354059  0.778503  0.817655

In [63]:
newDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       330 non-null    float64
 1   1       330 non-null    float64
 2   2       330 non-null    float64
 3   3       330 non-null    float64
 4   4       330 non-null    float64
dtypes: float64(5)
memory usage: 13.0 KB

In [64]:
newDf.describe()

                0           1           2           3           4
count  330.000000  330.000000  330.000000  330.000000  330.000000
mean     0.501586    0.509361    0.512084    0.494178    0.502866
std      0.290265    0.296556    0.289057    0.283248    0.279102
min      0.001047    0.004682    0.003631    0.000593    0.004340
25%      0.261284    0.247590    0.258516    0.241958    0.262955
50%      0.502276    0.508162    0.520090    0.492633    0.496960
75%      0.763566    0.773882    0.758072    0.732138    0.740819
max      0.997378    0.998848    0.999655    0.995311    0.997587

In [65]:
newDf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

# Change the value inside the dataframe

In [66]:
newDf[0][0]= 10000.0

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13556\1615845312.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newDf[0][0]= 10000.0

In [67]:
newDf

                0         1         2         3         4
0    10000.000000  0.743549  0.157163  0.304643  0.893568
1        0.576556  0.624649  0.153145  0.416081  0.557485
2        0.155813  0.691920  0.205322  0.460346  0.455982
3        0.903230  0.523042  0.650255  0.917147  0.506985
4        0.555209  0.612642  0.572181  0.785824  0.379464
..            ...       ...       ...       ...       ...
325      0.838049  0.005857  0.255985  0.237696  0.815358
326      0.977477  0.928928  0.056839  0.675184  0.491771
327      0.763955  0.073330  0.853605  0.651727  0.211867
328      0.078529  0.333257  0.721789  0.901435  0.098185
329      0.122808  0.848746  0.354059  0.778503  0.817655

[330 rows x 5 columns]

In [68]:
newDf.head()

              0         1         2         3         4
0  10000.000000  0.743549  0.157163  0.304643  0.893568
1      0.576556  0.624649  0.153145  0.416081  0.557485
2      0.155813  0.691920  0.205322  0.460346  0.455982
3      0.903230  0.523042  0.650255  0.917147  0.506985
4      0.555209  0.612642  0.572181  0.785824  0.379464

# Transpose

In [69]:
newDf.T

,0,1,2,3,4,5,6,7,8,9,...,320,321,322,323,324,325,326,327,328,329
0,10000.000000,0.576556,0.155813,0.903230,0.555209,0.224344,0.623440,0.616418,0.902023,0.201896,...,0.657640,0.801056,0.961487,0.673869,0.083614,0.838049,0.977477,0.763955,0.078529,0.122808
1,0.743549,0.624649,0.691920,0.523042,0.612642,0.248224,0.373522,0.796049,0.619910,0.305714,...,0.648075,0.411944,0.005659,0.528344,0.402692,0.005857,0.928928,0.073330,0.333257,0.848746
2,0.157163,0.153145,0.205322,0.650255,0.572181,0.330029,0.616710,0.871439,0.134506,0.832233,...,0.838419,0.754584,0.589862,0.933350,0.895491,0.255985,0.056839,0.853605,0.721789,0.354059
3,0.304643,0.416081,0.460346,0.917147,0.785824,0.945930,0.493079,0.555758,0.329835,0.741665,...,0.068817,0.124938,0.921939,0.637638,0.671024,0.237696,0.675184,0.651727,0.901435,0.778503
4,0.893568,0.557485,0.455982,0.506985,0.379464,0.458599,0.386085,0.481352,0.198268,0.792517,...,0.396630,0.674143,0.327753,0.321223,0.264959,0.815358,0.491771,0.211867,0.098185,0.817655

# Sorting

In [70]:
newDf.sort_index(axis=0)

                0         1         2         3         4
0    10000.000000  0.743549  0.157163  0.304643  0.893568
1        0.576556  0.624649  0.153145  0.416081  0.557485
2        0.155813  0.691920  0.205322  0.460346  0.455982
3        0.903230  0.523042  0.650255  0.917147  0.506985
4        0.555209  0.612642  0.572181  0.785824  0.379464
..            ...       ...       ...       ...       ...
325      0.838049  0.005857  0.255985  0.237696  0.815358
326      0.977477  0.928928  0.056839  0.675184  0.491771
327      0.763955  0.073330  0.853605  0.651727  0.211867
328      0.078529  0.333257  0.721789  0.901435  0.098185
329      0.122808  0.848746  0.354059  0.778503  0.817655

[330 rows x 5 columns]

In [71]:
newDf.sort_index(axis=0, ascending=False)

                0         1         2         3         4
329      0.122808  0.848746  0.354059  0.778503  0.817655
328      0.078529  0.333257  0.721789  0.901435  0.098185
327      0.763955  0.073330  0.853605  0.651727  0.211867
326      0.977477  0.928928  0.056839  0.675184  0.491771
325      0.838049  0.005857  0.255985  0.237696  0.815358
..            ...       ...       ...       ...       ...
4        0.555209  0.612642  0.572181  0.785824  0.379464
3        0.903230  0.523042  0.650255  0.917147  0.506985
2        0.155813  0.691920  0.205322  0.460346  0.455982
1        0.576556  0.624649  0.153145  0.416081  0.557485
0    10000.000000  0.743549  0.157163  0.304643  0.893568

[330 rows x 5 columns]

In [72]:
newDf.sort_index(axis=1)

                0         1         2         3         4
0    10000.000000  0.743549  0.157163  0.304643  0.893568
1        0.576556  0.624649  0.153145  0.416081  0.557485
2        0.155813  0.691920  0.205322  0.460346  0.455982
3        0.903230  0.523042  0.650255  0.917147  0.506985
4        0.555209  0.612642  0.572181  0.785824  0.379464
..            ...       ...       ...       ...       ...
325      0.838049  0.005857  0.255985  0.237696  0.815358
326      0.977477  0.928928  0.056839  0.675184  0.491771
327      0.763955  0.073330  0.853605  0.651727  0.211867
328      0.078529  0.333257  0.721789  0.901435  0.098185
329      0.122808  0.848746  0.354059  0.778503  0.817655

[330 rows x 5 columns]

In [73]:
newDf.sort_index(axis=1, ascending=False)

            4         3         2         1             0
0    0.893568  0.304643  0.157163  0.743549  10000.000000
1    0.557485  0.416081  0.153145  0.624649      0.576556
2    0.455982  0.460346  0.205322  0.691920      0.155813
3    0.506985  0.917147  0.650255  0.523042      0.903230
4    0.379464  0.785824  0.572181  0.612642      0.555209
..        ...       ...       ...       ...           ...
325  0.815358  0.237696  0.255985  0.005857      0.838049
326  0.491771  0.675184  0.056839  0.928928      0.977477
327  0.211867  0.651727  0.853605  0.073330      0.763955
328  0.098185  0.901435  0.721789  0.333257      0.078529
329  0.817655  0.778503  0.354059  0.848746      0.122808

[330 rows x 5 columns]

In [74]:
newDf.head()

              0         1         2         3         4
0  10000.000000  0.743549  0.157163  0.304643  0.893568
1      0.576556  0.624649  0.153145  0.416081  0.557485
2      0.155813  0.691920  0.205322  0.460346  0.455982
3      0.903230  0.523042  0.650255  0.917147  0.506985
4      0.555209  0.612642  0.572181  0.785824  0.379464

In [75]:
newDf[0][1]

np.float64(0.5765556331032506)

In [76]:
type(newDf[0])

pandas.core.series.Series

In [77]:
newDf

                0         1         2         3         4
0    10000.000000  0.743549  0.157163  0.304643  0.893568
1        0.576556  0.624649  0.153145  0.416081  0.557485
2        0.155813  0.691920  0.205322  0.460346  0.455982
3        0.903230  0.523042  0.650255  0.917147  0.506985
4        0.555209  0.612642  0.572181  0.785824  0.379464
..            ...       ...       ...       ...       ...
325      0.838049  0.005857  0.255985  0.237696  0.815358
326      0.977477  0.928928  0.056839  0.675184  0.491771
327      0.763955  0.073330  0.853605  0.651727  0.211867
328      0.078529  0.333257  0.721789  0.901435  0.098185
329      0.122808  0.848746  0.354059  0.778503  0.817655

[330 rows x 5 columns]

## view

In [78]:
newDfView=newDf

In [79]:
newDfView

                0         1         2         3         4
0    10000.000000  0.743549  0.157163  0.304643  0.893568
1        0.576556  0.624649  0.153145  0.416081  0.557485
2        0.155813  0.691920  0.205322  0.460346  0.455982
3        0.903230  0.523042  0.650255  0.917147  0.506985
4        0.555209  0.612642  0.572181  0.785824  0.379464
..            ...       ...       ...       ...       ...
325      0.838049  0.005857  0.255985  0.237696  0.815358
326      0.977477  0.928928  0.056839  0.675184  0.491771
327      0.763955  0.073330  0.853605  0.651727  0.211867
328      0.078529  0.333257  0.721789  0.901435  0.098185
329      0.122808  0.848746  0.354059  0.778503  0.817655

[330 rows x 5 columns]

In [80]:
newDfView[0][0]=765

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13556\4063526219.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newDfView[0][0]=765

In [81]:
newDf.head()

            0         1         2         3         4
0  765.000000  0.743549  0.157163  0.304643  0.893568
1    0.576556  0.624649  0.153145  0.416081  0.557485
2    0.155813  0.691920  0.205322  0.460346  0.455982
3    0.903230  0.523042  0.650255  0.917147  0.506985
4    0.555209  0.612642  0.572181  0.785824  0.379464

In [82]:
newDfView.head()

            0         1         2         3         4
0  765.000000  0.743549  0.157163  0.304643  0.893568
1    0.576556  0.624649  0.153145  0.416081  0.557485
2    0.155813  0.691920  0.205322  0.460346  0.455982
3    0.903230  0.523042  0.650255  0.917147  0.506985
4    0.555209  0.612642  0.572181  0.785824  0.379464

In [83]:
newDfCopy=newDf.copy()

In [84]:
newDfCopy[0][0]=656

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13556\2532441962.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newDfCopy[0][0]=656

In [85]:
newDf.head()

            0         1         2         3         4
0  765.000000  0.743549  0.157163  0.304643  0.893568
1    0.576556  0.624649  0.153145  0.416081  0.557485
2    0.155813  0.691920  0.205322  0.460346  0.455982
3    0.903230  0.523042  0.650255  0.917147  0.506985
4    0.555209  0.612642  0.572181  0.785824  0.379464

In [86]:
newDfCopy.head()

            0         1         2         3         4
0  656.000000  0.743549  0.157163  0.304643  0.893568
1    0.576556  0.624649  0.153145  0.416081  0.557485
2    0.155813  0.691920  0.205322  0.460346  0.455982
3    0.903230  0.523042  0.650255  0.917147  0.506985
4    0.555209  0.612642  0.572181  0.785824  0.379464

In [87]:
import pandas as pd

# Create a sample DataFrame
data = {
    "Student": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
   Student  Marks  Age
0     Ali     85   20
1    Sara     92   21
2   Bilal     76   19
3    Hina     89   22

In [88]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  4 non-null      object
 1   Marks    4 non-null      int64
 2   Age      4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes
None

In [89]:
print("\nDescribe:\n", df.describe())

Describe:
            Marks        Age
count   4.000000   4.000000
mean   85.500000  20.500000
std     6.952218   1.290994
min    76.000000  19.000000
25%    82.750000  19.750000
50%    87.000000  20.500000
75%    89.750000  21.250000
max    92.000000  22.000000

In [90]:
# -----------------------------
# 2. SORTING
# -----------------------------
print("\nSorting by Marks (descending):\n", df.sort_values("Marks", ascending=False))
print("\nSorting by Age (ascending):\n", df.sort_values("Age"))

Sorting by Marks (descending):
   Student  Marks  Age
1    Sara     92   21
3    Hina     89   22
0     Ali     85   20
2   Bilal     76   19

Sorting by Age (ascending):
   Student  Marks  Age
2   Bilal     76   19
0     Ali     85   20
1    Sara     92   21
3    Hina     89   22

In [91]:
# -----------------------------
# 3. TRANSPOSE
# -----------------------------
print("\nTransposed DataFrame:\n", df.T)

Transposed DataFrame:
            0     1      2     3
Student  Ali  Sara  Bilal  Hina
Marks     85    92     76    89
Age       20    21     19    22

## Slicing through loc function

In [92]:
import pandas as pd

# Sample DataFrame
data = {
    "Name": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
     Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [93]:
# 1. Select row with label 2
print(df.loc[2])

Name     Bilal
Marks       76
Age         19
Name: 2, dtype: object

In [94]:
# 2. Select specific rows and columns by NAME
print(df.loc[1:3, ["Name", "Marks"]])

    Name  Marks
1   Sara     92
2  Bilal     76
3   Hina     89

In [95]:

# 3. Applying Filter: Conditional selection: students with Marks > 85
print(df.loc[df["Marks"] > 85])

   Name  Marks  Age
1  Sara     92   21
3  Hina     89   22

##  Slicing through iloc

In [96]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [97]:
# 1. Select row at index 0
print(df.iloc[0])

Name     Ali
Marks     85
Age       20
Name: 0, dtype: object

In [98]:
# 2. Select 2 rows and 2 columns by position
print(df.iloc[0:2, 0:2])

   Name  Marks
0   Ali     85
1  Sara     92

In [99]:
# 3. Select last row using negative index
print(df.iloc[-1])

Name     Hina
Marks      89
Age        22
Name: 3, dtype: object

# Dropping the Row

In [100]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [101]:
df.drop(0).head()

    Name  Marks  Age
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

# Dropping the col

In [102]:
df.drop(['Age'], axis=1).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [103]:
df.head()

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [104]:
df.drop(['Age'], axis=1, inplace=True)

In [105]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [106]:
df.reset_index().head()

   index   Name  Marks
0      0    Ali     85
1      1   Sara     92
2      2  Bilal     76
3      3   Hina     89

In [107]:
df.reset_index(drop=True).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [108]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [109]:
df.reset_index(drop=True, inplace=True)

In [110]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

# Groupby
The groupby method allows you to group rows of data together and call aggregate functions

​
​

In [111]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [112]:
df = pd.DataFrame(data)

In [113]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

### Now you can use the .groupby() method to group rows together based off of a column name.
For instance let's group based off of Company. This will create a DataFrameGroupBy object:

In [114]:
df.groupby('Company')

##### You can save this object as a new variable:

In [115]:
by_comp = df.groupby("Company")
type(by_comp)

pandas.core.groupby.generic.DataFrameGroupBy

#### And then call aggregate methods of the object:

In [116]:
by_comp.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [118]:
df.groupby('Company').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
by_comp.std()

AttributeError: 'DataFrameGroupBy' object has no attribute 'sam'

In [121]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [122]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [123]:
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [124]:
by_comp.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0